apiVersion: batch/v1
kind: Job
metadata:
  name: copy-certs
spec:
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: ubuntu
        name: copy-certs
        command: ["cp"]
        args: ["/certs/registry.crt", "/tmp-certs"]
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
          - name: host-cert-dir
            mountPath: /tmp-certs
      volumes:
      - name: host-cert-dir
        hostPath:
          path: /usr/local/share/ca-certificates
          type: Directory
      - name: certs
        secret:
          secretName: certs
          optional: false