apiVersion: batch/v1
kind: Job
metadata:
  name: restart-docker
spec:
  activeDeadlineSeconds: 100
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker
      restartPolicy: Never
      hostPID: true
      hostIPC: true
      containers:
      - name: restart-docker
        image: ubuntu
        command: ["pkill"]
        args: ["-9", "dockerd"]
        securityContext:
          privileged: true