version: "3"
services:
  app:
    build: ./sample-vulnerable-java-app
    ports:
    - "8000:8000"
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_TRACE_AGENT_PORT=8126
    - DD_APPSEC_ENABLED=true
    - DD_TRACE_SAMPLE_RATE=1
    - DD_PROFILING_ENABLED=true
    - DD_LOGS_INJECTION=true
    - DD_SERVICE=my-sample-vulnerable-app
    - DD_VERSION=1.0
    - DD_ENV=production
    - DD_CWS_ENABLED=true
    links:
      - datadog-agent
    depends_on:
    - datadog-agent
  datadog-agent:
    image: gcr.io/datadoghq/agent
    pid: host
    privileged: true
    security_opt:
    - seccomp:unconfined
    cap_add:
    - SYS_ADMIN
    - SYS_RESOURCE
    - SYS_PTRACE
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    - IPC_LOCK
    - CHOWN
    environment:
    - DD_API_KEY=${DD_API_KEY:?Please set your DD API KEY}
    - DD_ENV=${DD_ENV:-development}
    - DD_APM_ENABLED=true
    - DD_LOGS_ENABLED=true
    - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    - DD_PROCESS_AGENT_ENABLED=true
    - DD_AC_EXCLUDE=name:datadog-agent
    #- DD_RUNTIME_SECURITY_CONFIG_ENABLED=true
    #- DD_RUNTIME_SECURITY_CONFIG_NETWORK_ENABLED=true # CWS network events
    - HOST_ROOT=/host/root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /:/host/root:ro
    - /sys/kernel/debug:/sys/kernel/debug
    - /etc/os-release:/etc/os-release
    ports:
    - "8126:8126/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8126/info"]
      interval: 30s
      timeout: 10s
      retries: 5