apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: instruqt
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    apm:
      enabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: 'false'
    image:
      name: 'datadog/agent:7.35.0'
    config:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  clusterAgent:
    image:
      name: 'datadog/cluster-agent:1.15.0'
