#!/bin/bash
if ! grep "$1" /root/status.txt;then
  clear
  echo "Waiting for $1"
  echo -ne This can take a minute or two...
  sleep 1
fi

while ! grep "$1" /root/status.txt; do 
  sleep 1
  echo -ne .
done

echo "Moving to the next step"