apiVersion: batch/v1
kind: Job
metadata:
  name: update-ca-certificates
spec:
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      hostPID: true
      containers:
      - name: update-ca-certificates
        image: ubuntu
        command: ["/usr/sbin/update-ca-certificates"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: usr
            mountPath: /usr
            readOnly: true
          - name: etc
            mountPath: /etc
      volumes:
      - name: usr
        hostPath:
          path: /usr
          type: Directory
      - name: etc
        hostPath:
          path: /etc
          type: Directory