apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: discounts
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      run: discounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: discounts
    spec:
      containers:
      - image: arapulido/ecommerce-spree-discounts:latest
        name: discounts
        command: ["ddtrace-run"]
        args: ["flask", "run", "--port=5001", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "discounts.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_USER
            value: "user"
          - name: DATADOG_SERVICE_NAME
            value: "discountsservice"
          - name: DD_AGENT_HOST 
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_ANALYTICS_ENABLED
            value: "true"
        ports:
        - containerPort: 5001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: discounts
  name: discounts
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: discounts
  sessionAffinity: None
  type: ClusterIP