version: '3'
services:
  agent:
    image: "datadog/agent:7.21.0"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_ENV=synthetics-intro
      - DD_SYSTEM_PROBE_ENABLED=true 
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug 
    cap_add:
      - SYS_ADMIN 
      - SYS_RESOURCE 
      - SYS_PTRACE 
      - NET_ADMIN 
      - IPC_LOCK 
    security_opt:
      - apparmor:unconfined  
    labels:
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "agent"}]'
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_SERVICE=discounts-service
      - DD_VERSION=1.0
      - DD_ENV=synthetics-intro
    image: "ddtraining/discounts-service-fixed:latest"
    command: [sh, -c, "pip install ddtrace -U && ddtrace-run flask run --port=5001 --host=0.0.0.0"]
    ports:
      - "5001:5001"
    volumes:
      - /ecommworkshop/discounts-service-fixed:/app
    depends_on:
      - agent
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "discounts-service"}]'
      com.datadoghq.tags.service: 'discounts-service'
      com.datadoghq.tags.env: 'synthetics-intro'
  frontend:
    environment:
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DB_USERNAME
      - DB_PASSWORD
      - DD_CLIENT_TOKEN
      - DD_APPLICATION_ID
      - DD_SERVICE=store-frontend
      - DD_VERSION=1.0
      - DD_ENV=synthetics-intro
    image: "ddtraining/ecommerce-frontend:latest"
    command: sh docker-entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - /ecommworkshop/store-frontend-instrumented-fixed:/spree
    depends_on:
      - agent
      - db
      - discounts
      - advertisements
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "store-frontend"}]'
      com.datadoghq.tags.service: 'store-frontend'
      com.datadoghq.tags.env: 'synthetics-intro'
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_SERVICE=advertisements-service
      - DD_VERSION=1.0
      - DD_ENV=synthetics-intro
    image: "ddtraining/advertisements-service:latest"
    command: [sh, -c, "pip install ddtrace -U && ddtrace-run flask run --port=5002 --host=0.0.0.0"]
    ports:
      - "5002:5002"
    volumes:
      - /ecommworkshop/ads-service:/app
    depends_on:
      - agent
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "advertisements-service"}]'
      com.datadoghq.tags.service: 'advertisements-service'
      com.datadoghq.tags.env: 'synthetics-intro'
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_SERVICE=postgres
      - DD_VERSION=1.0
      - DD_ENV=synthetics-intro
    labels:
      com.datadoghq.ad.logs: '[{"source": "postgresql", "service": "postgres"}]'
      com.datadoghq.tags.service: 'advertisements-service'
      com.datadoghq.tags.env: 'synthetics-intro'