apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: instruqt
  credentials:
    apiSecret:
      secretName: my-datadog-operator-apikey
      keyName: api-key
    appSecret:
      secretName: my-datadog-operator-appkey
      keyName: app-key
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: 'false'
      - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
        value: 'true'
      - name: DD_APM_NON_LOCAL_TRAFFIC
        value: 'true'
      - name: DD_LOGS_ENABLED
        value: 'true'
      - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
        value: 'true'
    image:
      name: 'datadog/agent:7.35.0'
    apm:
      enabled: true
      hostPort: 8126
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
    config:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  clusterAgent:
    image:
      name: 'datadog/cluster-agent:1.12.0'
  features:
    orchestratorExplorer:
      enabled: true
