version: '3.5'

networks:
  labnet:
    name: labnet
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: "lab-bridge-0"
      com.docker.network.bridge.enable_ip_masquerade: "true"

services:
  db:
    container_name: cicd-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gogs"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "gogs"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Dump file from pg_dump to seed the DB
    volumes:
      - /root/lab/cicd/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - labnet
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12.3
    depends_on:
      - db
    ports:
      - "8300:3000"
      - "8322:22"
    # Configuration file and starter repo
    volumes:
      - /root/lab/cicd/gogs.app.ini:/data/gogs/conf/app.ini
      - /root/lab/cicd/labuser.git:/data/git/gogs-repositories/labuser
    networks:
      - labnet
  registry:
    container_name: registry
    image: registry:2.6.2
    # restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - labnet
