version: '3'
services:
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
    image: 'ddtraining/discounts:2.1.2'
    command:
      [
        sh,
        -c,
        'flask run --port=5001 --host=0.0.0.0',
      ]
    expose:
      - '5001'
    depends_on:
      - db
  frontend:
    image: 'ddtraining/storefront-fixed:2.1.2'
    command: sh docker-entrypoint.sh
    ports:
      - '3000:3000'
    depends_on:
      - db
      - discounts
      - advertisements
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
    image: 'ddtraining/advertisements:2.1.2'
    command:
      [
        sh,
        -c,
        'flask run --port=5002 --host=0.0.0.0',
      ]
    expose:
      - '5002'
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  puppeteer:
    image: buildkite/puppeteer:10.0.0
    volumes:
      - /root/puppeteer-mobile.js:/puppeteer.js
      - /root/puppeteer.sh:/puppeteer.sh
    environment:
      - STOREDOG_URL
      - PUPPETEER_TIMEOUT
    depends_on:
      - frontend
    command: bash puppeteer.sh
