version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=datadog101
      - POSTGRES_DB=quotes
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./word.sql:/docker-entrypoint-initdb.d/word.sql

volumes:
  redis_data:
  postgres_data: