#!/bin/bash

if [ ! -x "$(command -v jq)" ]; then
  echo "jq not installed"
  exit 0
fi

DDUSERINFO=$(curl -sX POST -H "Content-Type: application/json" -d '{"orgId": "'"$1"'"}' "https://ruspgpghi7.execute-api.us-east-2.amazonaws.com/dev/create-org-user")

# echo "$DDUSERINFO" | jq

if [ "$(echo "$DDUSERINFO"|jq -r .message)" == "Error creating user" ]; then
  echo "Error creating user"
fi

USERID=$(echo "$DDUSERINFO"|jq -r .user.userId)
LABUSER=$(echo "$DDUSERINFO"|jq -r .user.datadogHandle)
NEWPASSWORD=$(echo "$DDUSERINFO"|jq -r .user.password)
DD_API_KEY=$(echo "$DDUSERINFO"|jq -r .user.datadogApiKey)
DD_APP_KEY=$(echo "$DDUSERINFO"|jq -r .user.datadogAppKey)
DD_ORG_ID=$(echo "$DDUSERINFO"|jq -r .user.datadogOrgId)
DD_ORG_NAME=$(echo "$DDUSERINFO"|jq -r .user.datadogOrgName)
ACCOUNT_EXPIRATION=$(echo "$DDUSERINFO"|jq -r .user.expiration)
ACCOUNT_EXPIRATION_FORMATTED=$(echo "$DDUSERINFO"|jq -r .user.formattedExpiration)

export USERID=$USERID
export LABUSER=$LABUSER
export NEWPASSWORD=$NEWPASSWORD
export DD_API_KEY=$DD_API_KEY
export DD_APP_KEY=$DD_APP_KEY
export DD_ORG_ID=$DD_ORG_ID
export DD_ORG_NAME=$DD_ORG_NAME
export ACCOUNT_EXPIRATION=$ACCOUNT_EXPIRATION
export ACCOUNT_EXPIRATION_FORMATTED=$ACCOUNT_EXPIRATION_FORMATTED
