tee -a /root/.bashrc <<EOF
export USERID=$USERID
export LABUSER=$LABUSER
export NEWPASSWORD=$NEWPASSWORD
export DD_API_KEY=$DD_API_KEY
export DD_APP_KEY=$DD_APP_KEY
export DD_ORG_ID=$DD_ORG_ID
export ACCOUNT_EXPIRATION=$ACCOUNT_EXPIRATION
EOF
