apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumps-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: pumps-service
  template:
    metadata:
      labels:
        app: pumps-service
    spec:
      containers:
      - name: pumps-service
        image: burningion/k8s-distributed-tracing-pumps:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: FLASK_APP
          value: 'thing'
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: FLASK_DEBUG
          value: '1'
        - name: FLASK_RUN_PORT
          value: '5001'
        - name: DATADOG_SERVICE_NAME
          value: 'pumps-service'
        - name: DD_ANALYTICS_ENABLED
          value: 'true'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user
              key: token
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: token
---
apiVersion: v1
kind: Service
metadata:
  name: pumps-service
spec:
  selector:
    app: pumps-service
  ports:
  - name: http
    protocol: TCP
    port: 5001
  type: NodePort