apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: traffic-replay
  name: traffic-replay
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: traffic-replay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: traffic-replay
    spec:
      containers:
        - command: ['/bin/sh']
          args: ['-c', 'while true; do wget frontend.default; sleep 5;done']
          image: busybox
          name: busybox
          resources: {}