apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: regular-traffic
  name: regular-traffic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: regular-traffic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: regular-traffic
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "while true; do wget nginx; sleep 5;done"]
        image: busybox
        name: busybox
        resources: {}
