apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args:
    - minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: localvolume
  volumes:
  - name: localvolume
    hostPath:
      path: /root/lab/minio
      type: DirectoryOrCreate

## TODO: Create a service and ingress so that the API and console can be browsed.