---
datadog:
  logs:
    enabled: true
    containerCollectAll: true
agents:
  useConfigMap: true
  customAgentConfig:
    kubelet_tls_verify: false
    vector:
      logs:
        enabled: true
        url: http://vector.vector:8282
      metrics:
        enabled: true
        url: http://vector.vector:8282